#! /bin/bash

DIR=$(dirname "$(readlink -f $0)")

electrum_config="/etc/electrum.conf"
function read_config()
{
    text=$1
    out=`grep -e ^$text $electrum_config |awk -F\= '{print $2}' | tail -n 1| tr -d ' '`
    echo $out
}

# read username
user=$(read_config "username")

case "$1" in
  start)
        su $user -c $DIR/start
    ;;
  stop)
        su $user -c $DIR/stop
    ;;
  status)
        su $user -c $DIR/status
    ;;
  info)
        su $user -c "/usr/bin/python $DIR/server.py info"
    ;;
  restart)
    $0 stop
    $0 start
    ;;
  *)
    echo "Usage: electrum-server {start|stop|restart|status}"
    exit 1
    ;;
esac

exit 0
