#! /bin/bash

# get PID of server
if ! PID=`electrum_server.py getpid`; then
    PID=""
fi

electrum_config="/etc/electrum.conf"
if [ ! -f $electrum_config ]; then
    echo "$electrum_config does not exist"
    exit
fi

function read_config()
{
    text=$1
    echo `grep -e ^$text $electrum_config |awk -F\= '{print $2}' | tail -n 1| tr -d ' '`
}

# read path from config
path=$(read_config "path")
# read username
user=$(read_config "username")


case "$1" in
    start)
	if [ "$PID" ]; then
	    echo "Server already running (pid $PID)"
	    exit
	fi

	if ! [ "$path" ]; then
	    echo "Variable path not set in $electrum_config"
	    exit
	fi

	if [ -f $path/electrum.log ]; then
	    mv $path/electrum.log $path/electrum.log.1
	fi

	echo "Starting server as daemon"
        su $user -c "ulimit -n 65536; nohup electrum_server.py &> $path/electrum.log &"
	;;
    stop)
	if [ ! $PID ]; then
	    echo "Server not running"
	else
            su $user -c "electrum_server.py stop"
	    echo "Waiting until process $PID terminates..."
	    while ps -p $PID > /dev/null; do sleep 1; done
	    echo "Done."
	fi
	;;
    status)
	if [ ! $PID ]; then
	    echo "Server not running"
	else
	    echo "Server running (pid $PID)"
	fi
	;;
    info)
	if [ ! $PID ]; then
	    echo "Server not running"
	else
            su $user -c "electrum_server.py info"
	fi
	;;
    restart)
	$0 stop
	$0 start
	;;
    *)
	echo "Usage: electrum-server {start|stop|restart|status|info}"
	exit 1
	;;
esac

exit 0
