#!/bin/bash

if [ "$(id -u)" == "0" ]; then
   echo "Remember you don't have to run electrum server as root. Consider using a non priviled user." 1>&2
   exit 1
fi

PID=`/usr/bin/python server.py getpid`
if [[ $PID != *[!0-9]* ]]; then
    echo "Server already running (pid $PID)"
    exit
fi

electrum_config="/etc/electrum.conf"

if [ ! -f $electrum_config ]; then
    echo "$electrum_config does not exist"
    exit
fi

path=`grep -e ^path_fulltree $electrum_config |awk -F\= '{print $2}' | tail -n 1`

if ! [ "$path" ]; then
    echo "Variable path_fulltree not set in $electrum_config"
    exit
    # we're actually forcing fulltree with this clause, which is ok if displaying v0.9 should use fulltree 
fi

rmdir $path --ignore-fail-on-non-empty

if [ ! -d $path ]; then
    echo "Database not found in $path."
    read -p "Do you want to download it from the Electrum foundry to $path ? " -n 1 -r
    echo
    if [[ $REPLY =~ ^[Yy]$ ]]; then
	mkdir -p $path
	wget -O - "http://foundry.electrum.org/leveldb-dump/electrum-fulltree-100-latest.tar.gz" | tar --extract --gunzip --strip-components 1 --directory $path --file -
    fi
fi

log_dir=/home/$USER/log

if [ ! -d $log_dir ]; then
    echo "Created logging directory in $USER's home."
    mkdir -p $log_dir
fi

datetime=$(date +'%Y-%m-%d_%H:%M')

echo "Starting server as daemon"
nohup /usr/bin/python -u server.py &> $log_dir/electrum_$datetime.log &
